name: main

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, prefix:  mingw-w64-x86_64 },
          { msystem: MINGW32, prefix:  mingw-w64-i686 },
          { msystem: UCRT64,  prefix:  mingw-w64-ucrt-x86_64 },
          { msystem: CLANG64, prefix:  mingw-w64-clang-x86_64 },
        ]

    name: ${{ matrix.msystem }}
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            ${{ matrix.prefix }}-meson
            ${{ matrix.prefix }}-ninja
            ${{ matrix.prefix }}-cc

      - name: Add staging repo
        shell: msys2 {0}
        run: |
          sed -i '1s|^|[staging]\nServer = https://repo.msys2.org/staging/\nSigLevel = Never\n|' /etc/pacman.conf

      - name: Update using staging
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'

      - name: Run Tests
        shell: msys2 {0}
        run: |
          meson _build --werror
          meson compile -C _build
          meson test -C _build
